
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: transcribe/transcribe.ipynb

import whisper
import mlx_whisper
import soundfile as sf
import torch
import subprocess
from pydub import AudioSegment
import os
import re
import logging
import warnings
import shutil
import logs

#import noisereduce as nr
#import librosa

tag="TRANSCRIBE"
'''
El módulo TRANSCRIBE sirve para hacer transcripciones automáticas de ficheros. Presenta las siguientes
funcionalidades.
'''

WHISPER_BASE="base"
WHISPER_MEDIUM="medium"
WHISPER_LARGE="large-v2"

MLX_WHISPER_LARGE="large"

# funciones de uso de audio, conversión y troceo de ficheros con pydub. También, mover y eliminar ficheros

def borrar_fichero(root, file_name, file_extension):
    """
    Elimina uun fichero de un directorio específico.

    Parámetros:
        root (str): Ruta del directorio donde se encuentra el archivo.
        file_name (str o list): Nombre del archivo o lista de archivos sin extensión.
        file_extension (str): Extensión del archivo (ej: '.txt', '.csv').

    Si el archivo no existe, se genera un mensaje de advertencia en lugar de lanzar una excepción.
    """

    method="borrar_fichero"

    file_path = os.path.join(root, file_name + file_extension)

    if os.path.exists(file_path):
        try:
            os.remove(file_path)
            logging.info(f"{method}- eliminado: {file_path}")
        except Exception as e:
            logging.error(f"{method}-ERROR al eliminar {file_path}: {e}")
    else:
        logging.warning(f"{method}- Archivo no encontrado: {file_path}")

def mover_ficheros(root, ficheros, dir_destino, borrar_transcripcion=True):
    """
    Mueve uno o varios archivos a un directorio destino dentro del root.

    Parámetros:
        root (str): Ruta raíz donde se encuentran los archivos.
        ficheros (str o list): Nombre de archivo o lista de archivos a mover.
            Cuando se recibe una lista, es porque se ha partido el fichero de audio en varios y por tanto,
            hay varias ficheros de transcripciones.

            Esta variable tiene que venir con la ruta completa, es decir, root ya está incluido.
        dir_destino (str): Nombre del directorio de destino dentro del root.
    """
    method="mover_ficheros"

    dir_proceso=os.path.join(root, dir_destino)
    os.makedirs(dir_proceso, exist_ok=True)  # Asegura que el directorio existe

    #Tenemos siempre una lista
    lista_ficheros=[ficheros] if not isinstance(ficheros, list) else ficheros
    mover_transcripcion=False if not isinstance(ficheros, list) else True

    logging.debug(f"{method}-START moviendo {len(lista_ficheros)} ficheros {lista_ficheros} → {dir_proceso}")

    for file in lista_ficheros:
        try:
            #dst_path = os.path.join(dir_proceso, file)
            file_path=os.path.join(root, file)
            logging.debug(f"{method}- A mover: {file_path} → {dir_proceso}")
            shutil.move(file_path, dir_proceso)
            logging.debug(f"{method}- Movido: {file_path} → {dir_proceso}")

            if borrar_transcripcion:
                borrar_fichero(root, file_path, ".txt")
            elif mover_transcripcion:
                shutil.move(f"{file_path}.txt", dir_proceso)
                logging.debug(f"{method}- Movido fichero de transcripción: {file_path} → {dir_proceso}")

        except Exception as e:
            logging.error(f"{method}-ERROR Se ha produciedo error moviendo {file_path}: {e}")


def unifica_ficheros_txt(root, lista_ficheros, duracion_segmento=-1):
    """
    Une varios archivos de texto en un solo archivo, agregando marcas de tiempo si es necesario.

    Parámetros:
        root (str): Directorio donde se encuentran los archivos de texto.
        lista_ficheros_path (list): Lista de nombres de archivos (sin extensión .txt) a unificar.
        duracion_segmento (int): Duración en minutos de cada segmento. Si es -1, no se añaden marcas de tiempo.

    Retorna:
        str: Ruta del archivo de salida con los textos unificados.
    """

    method="unifica_ficheros_txt"

    #Generamos el nombre del fichero que queremos generar (se elimina el _amplificado, si estuviera, y el _xxx del número de fichero)
    file_texto =re.sub(r'_amplificado', '', lista_ficheros[0])
    file_texto =re.sub(r'_\d{2}', '', file_texto) + ".txt"
    file_texto_output = os.path.join(root, file_texto)
    logging.info(f"{method}-START fichero {file_texto_output}")

    #Abrimos el fichero de salida.
    with open(file_texto_output, 'w') as salida:
        i=0
        for file in lista_ficheros:
            file_origen = os.path.join(root, file)
            file_origen_text = os.path.join(root, f"{file_origen}.txt")

            #Si duración = -1 significa que no está troceado.
            if duracion_segmento!=-1:
                tiempo_inicio=i* duracion_segmento
                tiempo_final = (i+1) * duracion_segmento  # Calcula el tiempo en minutos

                salida.write(f"[{tiempo_inicio} - {tiempo_final} minutos]\n")

            with open(file_origen_text, 'r') as entrada:
                salida.write(entrada.read() + "\n")  # Agrega el contenido del archivo
            logging.debug(f"{method}- concatenado {file_origen_text}")

            i+=1

    return file_texto, file_texto_output

def convierte(root, file_name, file_extension, formato="m4a", formato_destino="mp3"):
    method="convierte"

    logging.info(f"{method}-START convirtiendo {file_name}{file_extension} de formato {formato} a {formato_destino}")

    file_destino=f"{file_name}.{formato_destino}"
    audio_file_path_ori = os.path.join(root, f"{file_name}{file_extension}")
    logging.info(f"{method}- fichero origen: {audio_file_path_ori}")
    audio_file_path_des = os.path.join(root, file_destino)
    logging.info(f"{method}- fichero destino: {audio_file_path_des}")

    try:
        if formato!="wma":
            logging.info(f"{method}- convirtiendo con dpub")
            audio = AudioSegment.from_file(audio_file_path_ori, format=formato)
            audio.export(audio_file_path_des, format=formato_destino, bitrate="192k")
        else:
            command = [
            "ffmpeg", "-i", audio_file_path_ori,
            "-vn", "-ar", "44100", "-ac", "2", "-b:a", "192k",
            audio_file_path_des
            ]
            logging.info(f"{method}- invocando a ffmpeg directamente {command}")
            subprocess.run(command, check=True)
    except Exception as e:
        logging.error(f"{method}-ERROR convrtiendo {audio_file_path_ori}: {e}")

    return file_name, f".{formato_destino}"


def trocea_fichero(root, file_name, file_extension, duracion_segmento=15):
    """
    Divide un archivo de audio en fragmentos más pequeños de duración fija.

    Parámetros:
        root (str): Ruta del directorio donde se encuentra el archivo de audio.
        file_name (str): Nombre del archivo sin la extensión.
        file_extension (str): Extensión del archivo de audio ('.mp3').
        duracion_segmento (int): Duración de cada fragmento en minutos (por defecto 15).

    Retorna:
        list: Lista de archivos generados.
    """

    method="trocea_fichero"
    logging.debug(f"{method}-START {file_name}{file_extension} en fragmentos de {duracion_segmento} minutos.")

    file_path=os.path.join(root, file_name + file_extension)
    audio = AudioSegment.from_mp3(file_path)
    duracion_total = len(audio) / (60 * 1000)  # Convertir a minutos
    logging.debug(f"{method}- fichero de {duracion_total:.2f} minutos.")

    #La duración es el número de minutos que nos pasen en milisegundos.
    duracion_fragmento=duracion_segmento*60*1000

    lista_ficheros=[]
    lista_ficheros_path=[]
    for i, inicio in enumerate(range(0, len(audio), duracion_fragmento)):
        #Dividimos el fichero en trozos.
        fragmento=audio[inicio:inicio + duracion_fragmento]

        file_proceso=f"{file_name}_{i:02d}{file_extension}"
        output_file_path = os.path.join(root,  file_proceso)

        if not os.path.exists(output_file_path):
            fragmento.export(output_file_path, format="mp3")
            logging.debug(f"{method}- {output_file_path} generado.")
        else:
            logging.debug(f"{method}- {output_file_path} ya existe.")

        #Añadimos a la lista
        lista_ficheros.append(file_proceso)
        lista_ficheros_path.append(output_file_path)

    return lista_ficheros, lista_ficheros_path



# funciones de uso de audio, trasncripción con whisper.

def transcribe_audio_to_text(root, file, libreria="WHISPER", modelo=WHISPER_BASE, lengua="es", temperature=0, compression_ratio_threshold=2.5, wordtimestamp=True):
    audio_file_path = os.path.join(root, file)
    audio_file_path_txt = os.path.join(root, f"{file}.txt")

    if libreria=="WHISPER":
        device = "mps" if torch.backends.mps.is_available() else "cpu"  # Usar Metal en Mac
        #device="cpu"
        # Cargar el modelo Whisper (puedes cambiar 'base' a otro tamaño del modelo si es necesario)
        model = whisper.load_model(modelo)#, device)

        # FORZAR USO DE float32 PARA EVITAR ERRORES EN MPS
        for param in model.parameters():
            param.data = param.data.to(torch.float32)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", category=UserWarning)
            result = model.transcribe(audio_file_path, language=lengua)

    elif libreria=="MLX_WHISPER":
        # Transcribir el audio
        os.environ["MLX_WHISPER_MODEL"] = modelo
        result = mlx_whisper.transcribe(audio_file_path, language=lengua)

    # Guardar la transcripción en un archivo de texto
    with open(audio_file_path_txt, "w") as f:
        f.write(result["text"])
        #for segment in result["segments"]:
        #    f.write(f"[{segment['start']:.2f}s - {segment['end']:.2f}s] {segment['text']}")

def procesa_transcripcion(root, lista_ficheros, libreria="WHISPER", modelo=WHISPER_BASE, duracion_segmento=10):
    method="procesa_transcripcion"

    dir_procesado="procesado"
    logging.debug(f"{method}-START lista_ficheros={lista_ficheros}, libreria={libreria}, modelo={modelo}, duración segmento={duracion_segmento}")

    for file in lista_ficheros:
        if not os.path.exists(os.path.join(root, f"{file}.txt")):
            transcribe_audio_to_text(root, file, libreria=libreria, modelo=modelo)
            logging.debug(f"{method}- Transcrito fichero {file} con modelo {modelo}")
        else:
            logging.debug(f"{method}- Fichero {file} ya transcrito")

    #unifica los ficheros generados
    logging.debug(f"{method}- longitud lista --> {len(lista_ficheros)}")
    if len(lista_ficheros) > 1:
        fichero_texto_unificado, fichero_texto_unificado_path=unifica_ficheros_txt(root, lista_ficheros, duracion_segmento)
        logging.debug(f"{method}- Unificado fichero. Resultado={fichero_texto_unificado_path}")

        #Sólo si trocea, mueve los ficheros parciales, y sus transcripciones, al directorio de procesados.
        mover_ficheros(root, lista_ficheros, dir_procesado)
        logging.debug(f"{method}- Ficheros movidos ({lista_ficheros})")
    else:
        fichero_texto_unificado=f"{lista_ficheros[0]}.txt"
        fichero_texto_unificado_path=os.path.join(root, fichero_texto_unificado)
        logging.debug(f"{method}- No se unifica porque el fichero no se ha troceado. Resultado={fichero_texto_unificado_path}")

    #Mueve el fichero de texto unificado al directorio de procesado.
    mover_ficheros(root, fichero_texto_unificado, dir_procesado)
    logging.debug(f"{method}- Fichero movido ({fichero_texto_unificado})")

    fichero_texto_unificado_path = os.path.join(root, f"{dir_procesado}/{fichero_texto_unificado}")
    logging.debug(f"{method}- fichero unificado -> root:{root}, fichero texto:{fichero_texto_unificado}, path_final: {fichero_texto_unificado_path}")

    return fichero_texto_unificado, fichero_texto_unificado_path


def amplifica_voz(root, file, file_extension):
    file_amplificado=f"{file}_amplificado"

    file_origen_path = os.path.join(root, file + file_extension)
    file_amplificado_path = os.path.join(root, file_amplificado + file_extension)

    if not os.path.exists(file_amplificado_path):
        comando=f'ffmpeg -i "{file_origen_path}" -af "speechnorm=e=20:r=0.0003:l=1" "{file_amplificado_path}"'
        os.system(comando)
        logging.debug(f" Creado file amplificado con nombre={file_amplificado_path} ")
    else:
        logging.debug(f" El fichero amplificado {file_amplificado_path} ya existe.")

    return file_amplificado



def genera_transcripcion_fichero(root, file, amplifica=True, elimina_fondo=False, trocea=True, duracion_segmento=28, log_level=logging.INFO):
    method="genera_transcripcion_fichero"

    logger, handler = logs.crea_log(log_level, method)
    logging.info(f"{method}-START Procesando fichero {file} con parametros: amplifica:{amplifica}, trocea:{trocea}, duración segmento:{duracion_segmento}")

    file_name, file_extension = os.path.splitext(file)
    old_extension = file_extension

    file_unificado="-1"
    file_unificado_path="-1"

    if file_extension.upper() in ('.M4A', '.WAV', '.MP3', '.WMA'):
        #No procesamos los ficheros que hemos generado ya, por si es un rearranque.
        if file_name.endswith("_amplificado") or re.search(r"_\d+$", file_name):
            logging.debug(f"{method}- Ignorado {file} por regla de nombres")

        #Usamos la variable file_proceso para poder ir cambiando el nombre
        file_convertido=file_name

        #convertimos a .wav o .mp3 para realizar la transcripción
        if file_extension.lower() in ('.m4a', '.wma'):
            file_convertido, file_extension = convierte(root, file_name, file_extension, formato=file_extension[1:4].lower())
            logging.info(f"{method}- -> Convertido fichero. Resultado={file_convertido}")

        #Amplificamos la voz
        file_amplificado=file_convertido
        if amplifica:
            file_amplificado = amplifica_voz(root, file_convertido, file_extension)
            logging.info(f"{method}- -> Amplificado fichero. Resultado={file_amplificado}")

        lista_ficheros = [file_amplificado + file_extension]
        lista_ficheros_path = [os.path.join(root, file_amplificado + file_extension)]
        if trocea:
            #Tenemos que trocear el fichero y transcribir cada trozo.
            lista_ficheros, lista_ficheros_path = trocea_fichero(root, file_amplificado, file_extension, duracion_segmento=duracion_segmento)
            logging.info(f"{method}- -> Ficheros troceados. Generados {len(lista_ficheros)} ficheros.")
        else:
            #No se ha generado segmentos porque no se ha troceado.
            duracion_segmento=-1

        file_unificado, file_unificado_path=procesa_transcripcion(root, lista_ficheros, libreria="WHISPER", modelo=WHISPER_LARGE, duracion_segmento=duracion_segmento)
        logging.info(f"{method}- -> Ficheros transcritos. Unificado en {file_unificado_path}")

        #Mueve el fichero original al directorio de originales.
        file_path=os.path.join(root, file)
        mover_ficheros(root, file_path, "originales")
        logging.info(f"{method}- -> Movido {file_path} a originales.")

        #Si se ha amplificado, elimina el fichero amplificado y convertido.
        if old_extension != file_extension:
            borrar_fichero(root, file_convertido, file_extension)
            logging.info(f"{method}- -> Borrado fichero convertido {file_convertido}.")

        if file_amplificado!=file_name:
            borrar_fichero(root, file_amplificado, file_extension)
            logging.info(f"{method}- -> Borrado fichero amplificado {file_amplificado}.")
    else:
        logging.warning(f"{method}- Fichero {file_name} no procesado.")

    logging.info(f"{method}-END ")
    logs.cierra_log(logger, handler)

    return file_unificado, file_unificado_path



def genera_transcripcion(disco_duro, usuario, carpeta, amplifica=True, elimina_fondo=False, trocea=True, duracion_segmento=28, log_level=logging.INFO):
    method="genera_transcripcion"

    logger, handler = logs.crea_log(log_level, method)

    # Crear el path completo a la carpeta de música
    directory = os.path.join(disco_duro, usuario, carpeta)
    logging.info(f"{method}-START Procesando el directorio: {directory}")

    total=0
    n=0

    for root, dirs, files in os.walk(directory):
        #Solo procesamos el directorio, no los subdirectorios.
        del dirs[:]
        logging.info(f"{method}- Encontrados {len(files)} a procesar.")
        n=1

        #Procesamos los ficheros del directorio.
        for file in files:
            genera_transcripcion_fichero(root, file, amplifica, elimina_fondo, trocea, duracion_segmento, log_level)
            n+=1
            #logging.info(f"{method}- -> {file} convertido.")

    total=total+n
    logging.info(f"{method}-END Total de ficheros -> {total}")

    logs.cierra_log(logger, handler)