
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: transcribe/file_manager.ipynb

import os
from PyPDF2 import PdfMerger


def concatenar_pdfs_en_directorios(directorio_raiz):
    for carpeta_actual, subcarpetas, archivos in os.walk(directorio_raiz):
        print(f"Iniciando caperta {carpeta_actual}")
        # Ignorar el directorio raíz si no quieres que se procese
        if carpeta_actual == directorio_raiz:
            continue

        # Filtrar archivos PDF
        pdfs = [f for f in archivos if f.lower().endswith(".pdf")]
        print(f"Encontrados {len(pdfs)} PDFs en {carpeta_actual}")
        if not pdfs:
            continue  # saltar si no hay PDFs

        # Ordenar por nombre
        pdfs.sort()

        # Crear el merger
        merger = PdfMerger()

        for pdf in pdfs:
            ruta_pdf = os.path.join(carpeta_actual, pdf)
            try:
                merger.append(ruta_pdf)
            except Exception as e:
                print(f"⚠️ No se pudo añadir {ruta_pdf}: {e}")

        # Nombre del PDF de salida = nombre de la carpeta
        nombre_carpeta = os.path.basename(carpeta_actual.rstrip(os.sep))
        pdf_salida = os.path.join(carpeta_actual, f"{nombre_carpeta}.pdf")

        try:
            merger.write(pdf_salida)
            print(f"✅ PDF combinado creado: {pdf_salida}")
        except Exception as e:
            print(f"❌ Error al escribir {pdf_salida}: {e}")
        finally:
            merger.close()

