
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: transcribe/logs.ipynb

import logging

def inicia_logs(log_level):
    method="inicia_logs"

    #Prepación de logs.
    for handler in logging.root.handlers[:]:
        logging.root.removeHandler(handler)
        handler.close()
    logging.basicConfig(level=log_level, format='%(asctime)s - %(levelname)s - %(message)s')

    logging.debug(f"{method}-START Logs iniciados")

def crea_log(log=logging.INFO, nombre="DEFECTO"):
    method="crea_log"

    logger = logging.getLogger(nombre)
    handler = logging.StreamHandler()
    handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
    logger.addHandler(handler)
    logger.setLevel(log)
    logger.propagate = False

    logging.debug(f"{method}-START Creado log con nombre {nombre}")

    return logger, handler

def cierra_log(logger, handler):
    logger.removeHandler(handler)
    handler.close()

def get_log(nombre):
    return logging.getLogger(nombre)
