
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: transcribe/ollama_manager.ipynb

#####
#####
# LLAMADA A API DE OLLAMA PARA GENERAR RESPUESTAS.
#####
#####

##### LEVEL 1 #####

import requests
import os
import json
import logging
import logs
import re

import httpx

import mimetypes

import shlex
import subprocess
from typing import Optional, Tuple

MODELO_DEFECTO="qwen3:30b-a3b"

#MICROSOFT
MODELO_PHI4_Q8="phi4:14b-q8_0"

#QWEN
MODELO_QWEN_1_5B="qwen2.5-coder:1.5b"
MODELO_QWEN3_30B_THINK="qwen3:30b-a3b-thinking-2507-q4_K_M"
MODELO_QWEN3_30B="qwen3:30b"
MODELO_QWEN2_5VL_7B="qwen2.5vl:32b"
MODELO_QWEN3_CODER="qwen3-coder:latest"

#MISTRAL
MODELO_MISTRAL_24B_Q8="mmistral-small3.2:latest"
MODELO_DEVSTRAL="devstral:latest"

#GEMMA
MODELO_GEMMA3_27B="gemma3:27b"

#OPEN AI
MODELO_OPENAI="gpt-oss:latest"

ELEMENTOS_PERMITIDOS=["funcion", "clase"]



class OllamaException(Exception):
    """
    CLASS.

    Represents a custom exception for errors related to calling the Ollama API.

    The `OllamaException` class inherits from the base `Exception` class and provides additional context for the error, including a custom message and any associated errors.

    The `__init__` method initializes the exception with the provided message, errors, and a default message indicating an error calling the Ollama API.
    """
    def __init__(self, message, errors="", messagio="Error calling ollama API"):

        # Call the base class constructor with the parameters it needs
        super(OllamaException, self).__init__(messagio + '-' + message, errors)

        # Now for your custom code...
        self.errors = errors



def separa_thinking_contenido(result):
    """
    Separa el contenido de la respuesta en dos partes:
        - La parte que contiene la razonamiento (think)
        - La parte que contiene el contenido del ticket
    """
    thinking_part =""
    content_part = result

    start_index = result.find("<think>")

    if start_index > -1:
        start_index += len("<think>")
        end_index = result.find("</think>")

        # Extraemos la cadena de razonamiento
        thinking_part = result[start_index:end_index]

        # Extraemos el contenido
        content_part = result[end_index + len("</think>"):]

    return content_part, thinking_part


def procesa_output(response):
    """
    FUNCTION. procesa_output

    Processes the output from the Ollama API response. This function takes the response object from the Ollama API call and extracts the relevant content from the
    JSON response. It handles different formats of the response, including the 'message' and 'response' keys, and returns a single string containing the processed output.

    Args:
        response (requests.Response): The response object from the Ollama API call.

    Returns:
        str: The processed output from the Ollama API response.
    """
    response_str=response.content.decode('utf-8')
    response_list=response_str.split('\n')
    cadena_output=[]
    for line in response_list:
        if line.strip():
            json_obj=json.loads(line)

            if 'message' in json_obj and 'content' in json_obj['message']:
                content_value = json_obj['message']['content']
            elif 'response' in json_obj:
                content_value = json_obj['response']
            else:
                content_value = "error en formato json"

            cadena_output.append(content_value)

    cadena_final=''.join(cadena_output)

    return cadena_final




def call_ollama_api_request(model, message, tipo='generate', temperature=0.5):
    """
    FUNCTION. call_ollama_api_request.

    Calls the Ollama API to generate a response based on the provided model, message, and request type.

    Args:
        model (str): The model to use for the API request.
        message (str): The message or prompt to send to the API.
        tipo (str, optional): The type of request to make, either 'generate' or another supported type as chat. Defaults to 'generate'.

    Returns:
        requests.Response: The response object from the API request.

    Raises:
        OllamaException: If the API request returns a non-200 status code.
    """

    method="call_ollama_api_request"

    url = f"http://localhost:11434/api/{tipo}"  # Cambia esta URL según tu configuración
    payload = {
        "model": model,
        "prompt": message,
        "raw" : True,
        "stream" : False,
        "options": {
            "temperature": temperature
        }
    }

    headers= {
        "Content-Type": "application/json",
    }

    logging.debug(f"{method}- url={url}, model={model}, tipo={tipo}, temperature={temperature}")
    response = requests.post(url, json=payload, headers=headers)
    if response.status_code == 200:
        return response
    else:
        raise OllamaException(f"Returned code: {response.status_code}, Response Text={response.text}")






from openai import OpenAI

api_base="http://localhost:11434/v1"
api_key="ollama"


def get_loaded_models():
    """
    Retrieves a list of all models currently loaded in Ollama.

    Returns:
        list: A list of model names.
    """
    method = "get_loaded_models"
    logging.debug(f"{method}-START")

    try:
        # Initialize the client with the API base and key
        client = OpenAI(
            base_url=api_base,
            api_key=api_key
        )

        # Make a request to get the list of loaded models
        response = client.models.list()

        # Extract the model names from the response
        models = [model.id for model in response.data]

        return models

    except Exception as e:
        logging.error(f"{method}-ERROR {str(e)}")
        raise OllamaException(f"Exception: {str(e)}")




def call_ollama_api(model, system_message, user_message, temperature=0.5, think=True, max_token=1000000, timeout=300.0):
    """
    FUNCTION. call_ollama_api.

    Calls the Ollama API, via python package, to generate a response based on the provided model, user message, and system_message.

    Args:
        model (str): The model to use for the API request.
        system_message (str): The message or prompt by system role to send to the API.
        user_message (str): The message or prompt by user role to send to the API.
        temperature (str, optional): temperature to ajust model imagination.

    Returns:
        requests.Response: The response object from the API request.

    Raises:
        OllamaException: If the API request returns a non-200 status code.
    """

    method="call_ollama_api"
    logging.debug(f"{method}-START with model={model}, temperature={temperature}, mensaje={user_message[0:100]}...")

    try:
        # Crear un timeout personalizado de 60 minutos (en cada fase de la petición)
        timeout = httpx.Timeout(
            connect=60.0,      # conexión: 1 minuto
            read=timeout,       # lectura de respuesta: 60 minutos
            write=60.0,        # escritura de payload: 10 minuto
            pool=None          # sin timeout en la conexión del pool
        )

        client = OpenAI(
            base_url = api_base,
            api_key = api_key,
            http_client=httpx.Client(timeout=timeout)
        )

        messages=[
            {"role":"system", "content": system_message},
            {"role": "user", "content": user_message}
        ]

        response=client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=temperature,
            extra_body={"think": think},
            max_tokens=max_token)

        try:
            reasoning = response.choices[0].message.reasoning
        except Exception as e:
            reasoning = None
        content = response.choices[0].message.content

        salida = f"<think>{reasoning}</think>{content}" if reasoning is not None  else content

        return salida
    except Exception as e:
        logging.error(f"{method}-ERROR {str(e)}")
        raise OllamaException(f"Exception: {str(e)}")



from mlx_vlm import load,generate
from mlx_vlm.video_generate import process_vision_info

import mlx.core as mx
from typing import Tuple

def split_thinking_and_answer(text: str) -> Tuple[str, str]:
    if not text:
        return "", ""

    text = text.strip()
    if "</think>" not in text:
        return "", text

    pattern = re.compile(r"(?:<think>\s*)?(.*?)\s*</think>\s*(.*)", re.DOTALL)
    match = pattern.fullmatch(text)

    if match:
        return match.group(1).strip(), match.group(2).strip()

def describe_video(
    video_path: str,
    prompt: str = "Resume brevemente el vídeo en 3-5 líneas: ¿qué se ve, quién sale y qué ocurre?. ¿Aparece una niña en el video?",
    model_id: str = "mlx-community/Qwen3.5-9B-MLX-4bit", #"mlx-community/Qwen3-VL-4B-Instruct-4bit",
    fps: float = 1.0,
    max_pixels=(224, 224),
    max_tokens: int = 4096,
    temperature: float = 0.6,
    timeout_sec: int = 600,
) -> str:
    """
    The function `describe_video` takes a video file path and makes a sumarization using the model_id parameter, by default qwen2.5-vl-7b.
    """
    # Load the model and processor
    model, processor = load(model_id)
    #model, processor = load("mlx-community/SmolVLM2-2.2B-Instruct-mlx")

    messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "video",
                "video": video_path,
                "max_pixels": 240 * 240,
                "fps": fps,
            },
            {"type": "text", "text": prompt},
        ],
    }]

    # Preparation for inference
    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    image_inputs, video_inputs = process_vision_info(messages)

    inputs = processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt",
    )

    # Convert inputs to mlx arrays
    input_ids = mx.array(inputs['input_ids'])
    pixel_values = mx.array(inputs['pixel_values_videos'])
    mask = mx.array(inputs['attention_mask'])
    video_grid_thw = mx.array(inputs['video_grid_thw'])

    kwargs = {
        "video_grid_thw": video_grid_thw,
    }

    kwargs["video"] = video_path
    kwargs["input_ids"] = input_ids
    kwargs["pixel_values"] = pixel_values
    kwargs["mask"] = mask
    #response = generate(model, processor, prompt=text, temperature=0.7, max_tokens=max_tokens, **kwargs)
    response = generate(
        model,
        processor,
        prompt=text,
        temperature=temperature,
        max_tokens=max_tokens,
        thinking_budget=2048,   # límite de tokens del bloque <think>
        input_ids=input_ids,
        pixel_values=pixel_values,
        mask=mask,
        video_grid_thw=video_grid_thw,
    )
    thinking, answer = split_thinking_and_answer(response.text)

    return answer

def describe_video2(
    video_path: str,
    prompt: str = (
        "Resume brevemente el vídeo en 3-5 líneas: qué se ve, quién sale y qué ocurre. "
        "Indica también si aparece una niña."
    ),
    model_id: str = "mlx-community/Qwen3.5-9B-MLX-4bit",
    fps: float = 1.0,
    max_pixels: tuple[int, int] = (224, 224),
    max_tokens: int = 1024,
    temperature: float = 0.2,
    thinking_budget: int | None = 256,
    enable_thinking: bool = True,
) -> str:
    """
    Describe un vídeo con un modelo VLM en MLX.

    Notas:
    - enable_thinking=True permite que el modelo use <think>...</think>.
    - thinking_budget limita cuántos tokens puede gastar dentro de ese bloque.
    - Esta versión usa una sola ruta coherente:
      1) apply_chat_template
      2) process_vision_info
      3) processor(...)
      4) generate(...) con tensores ya preparados
    """

    model, processor = load(model_id)

    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "video",
                    "video": video_path,
                    "max_pixels": max_pixels[0] * max_pixels[1],
                    "fps": fps,
                },
                {"type": "text", "text": prompt},
            ],
        }
    ]

    # Construye el prompt final del chat template.
    # En Qwen3.5, thinking se controla aquí; el budget se aplica en generate.
    text = processor.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking,
    )

    image_inputs, video_inputs = process_vision_info(messages)

    inputs = processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt",
    )

    input_ids = mx.array(inputs["input_ids"])
    attention_mask = mx.array(inputs["attention_mask"])
    pixel_values_videos = mx.array(inputs["pixel_values_videos"])

    gen_kwargs = {
        "input_ids": input_ids,
        "mask": attention_mask,
        "pixel_values": pixel_values_videos,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }

    # Algunos processors/modelos exponen video_grid_thw; si está, se pasa.
    if "video_grid_thw" in inputs:
        gen_kwargs["video_grid_thw"] = mx.array(inputs["video_grid_thw"])

    # thinking_budget está documentado en mlx-vlm reciente
    if thinking_budget is not None:
        gen_kwargs["thinking_budget"] = thinking_budget

    # IMPORTANTE:
    # No pasar prompt=text ni video=video_path aquí,
    # porque ya estamos usando los tensores preparados.
    response = generate(
        model,
        processor,
        prompt=prompt,
        **gen_kwargs,
    )

    raw_text = response.text if hasattr(response, "text") else str(response)
    _, answer = split_thinking_and_answer(raw_text)

    return answer or raw_text.strip()


###### RESUMENES DE FICHEROS

def genera_resumen(message, length="medium", model=MODELO_DEFECTO, max_token=5000):
    method="genera_resumen"

    system_message="""
    You are an IA specialized for making summary. You are rewarded for greats summary.\n
    Follow these instructions strictly:\n
    - Extract only the most relevant information.\n
    - Keep the tone clear and concise.\n
    - Use natural and fluent language.\n
    - Do not add extra information\n
    - Before answering think about if all key points are included. Add whatever some key point is not included.\n
    - Make sure that each key point is about 5 sentences long.
    - The answer must be in spanish.\n\n
    """
    user_message=(f"Summarize the following text in a {length} way, keeping key points clear and concise :\n\n"
                  f"'''{message}'''\n\n"
                  "Summary:")

    resumen = call_ollama_api(model=model, system_message=system_message, user_message=user_message, temperature=0.3, max_token=max_token)

    return resumen

def actualiza_resumen(resumen, message, length="medium", model=MODELO_DEFECTO, max_token=5000):
    method="genera_resumen"

    system_message="""
        You are an IA specialized for updating summary. You are rewarded for greats summary.
        You follow the instructions given strictly.\n
        You need two main input: a text, and a list of key points extracted already from the text. If you dont have both elements you should ask for them.\n
        Your mission is to update all of the key points, adding a detalied summary from the text where this point is treated.\n
    """

    user_message=f"""
        <system>
        Eres un asistente experto en comprensión y resumen de textos. Se te proporcionará una lista de puntos clave extraídos de un texto junto con el texto original.
        Tu tarea es completar cada punto clave agregando un resumen detallado de su contenido, asegurándote de mantener la coherencia y precisión del mensaje original.
        </system>
        <instrucciones>
        1. Piensa paso a paso.
        2. Antes de responder, asegurate que se incluyen todos los puntos claves de la lista proporcionada.
        3. Ubica la información relevante en el texto original.
        4. Expande cada punto clave con un resumen detallado y bien estructurado.
        5. Usa un tono claro y profesional, evitando repetir información innecesaria.
        6. Asegúrate de que cada resumen sea conciso pero informativo, sin inventar información adicional.
        </instrucciones>
        <lista puntos claves>
        **Lista de puntos clave extraídos del texto:**
        {resumen}
        </lista puntos claves>
        <texto original>
        {message}
        </texto original>
        <ejemplo salida esperada>
        ### ** Salida esperada (ejemplo de formato de respuesta):**
        **Punto 1:** [Primer punto clave]
        **Explicación detallada:** [Resumen detallado basado en el texto original]

        **Punto 2:** [Segundo punto clave]
        **Explicación detallada:** [Resumen detallado basado en el texto original]

        **Punto 3:** [Tercer punto clave]
        **Explicación detallada:** [Resumen detallado basado en el texto original]

        Etc. Asegurate de incluir todos los puntos claves.
        </ejemplo salida esperada>
        <idioma>
        1. Identifica el lenguaje del texto original.
        2. Haz el resumen en el lenguaje del texto original.
        </idioma>
    """

    resumen = call_ollama_api(model=model, system_message=system_message, user_message=user_message, temperature=0.3, max_token=max_token)

    return resumen



def procesa_resumen_fichero(file_path, log_level=logging.INFO, modelo_lista_puntos=MODELO_DEFECTO, modelo_resumen_detallado=MODELO_DEFECTO, maxtoken=10000):

    method="procesa_resumen_fichero"

    logger, handler = logs.crea_log(log_level, method)
    logging.info(f"{method}-START fichero {file_path}")
    fichero_resumen=file_path

    resumen="No se ha podido procesar el resumen."
    file_resumen_path="sin fichero"
    if os.path.exists(file_path):
        with open(file_path, "r") as f:
            #Leemos mensaje a resumir.
            mensaje=f.read()

            lista_puntos=genera_resumen(mensaje, "large",  model=modelo_lista_puntos, max_token=maxtoken)
            logging.debug(f"{method} lista de puntos generados.")

            resumen=actualiza_resumen(lista_puntos, mensaje, model=modelo_resumen_detallado, max_token=maxtoken)
            logging.debug(f"{method} resumen detallado generado.")

            base_nombre, extension = file_path.rsplit('.', 1)
            file_resumen_path = f"{base_nombre}_resumen.{extension}"

            with open(file_resumen_path, "w") as fo:
                fo.write(resumen)
    else:
        logging.info(f"{method}-  Fichero {file_path} no existe.")

    logging.info(f"{method}-END ")
    logs.cierra_log(logger, handler)

    return file_resumen_path, resumen