
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: transcribe/incidencias_manager.ipynb

import json
import logging
import pandas as pd
from typing import Any, Dict, Optional, Literal
import os
import math
import ollama_manager
import re

PROMPT_ANALIZA_TODAS="analiza_todas_incidencias"
PROMPT_ANALIZA_CAUSA_RAIZ="analiza_incidencia_causa_raiz"
PROMPT_GENERA_PROPUESTAS="genera_propuestas"
PROMPT_GENERA_PROMPT="genera_prompt_app"
PROMPT_GENERA_DESC_SOL="calcula_descripcion_solucion"
PROMPT_CONSOLIDA_ANALISIS_GENERAL="consolida_analisis_general"

LISTA_CAMPOS_SPAGNA=["Número", "Descripción", "Descripción corta", "Notas de resolución", "Notas de trabajo", "Estado", "Estado del incidente"]

# Tipos de prompt permitidos: mismos nombres que los métodos "vacíos"
PromptTipo = Literal[
    PROMPT_ANALIZA_TODAS,
    PROMPT_ANALIZA_CAUSA_RAIZ,
    PROMPT_GENERA_PROPUESTAS,
    PROMPT_GENERA_PROMPT,
    PROMPT_GENERA_DESC_SOL,
    PROMPT_CONSOLIDA_ANALISIS_GENERAL
]

"""
Variables internas que genera la clase:
    * _app_name -> Nombre de la aplicación con la que estamos trabajando.
    * _fichero_incidencias -> Path + Nombre del fichero de incidencias.
    * _apps -> Listado de apps configuradas en el fichero de apps.ini.
    * _promtps -> Listado de prompts configurados en el fichero de prompts.ini.
    *

Métodos internos:
    * _setPrompt -> Sirve para asignar un prompt leído del ficheor
"""



############################################################
############################################################
############################################################
## CLASE EXCEPCIÓN DE INCIDENCIAS


class IncidenciaException(Exception):
    """
    Excepción de dominio para tratar incidencias localmente.
    Úsala para capturarla en el mismo módulo/capa y decidir la acción
    (reintento, degradación, log, mensaje al usuario, etc.).
    """
    def __init__(self, mensaje: str | None = None, causa: Exception | None = None):
        super().__init__(mensaje if mensaje is not None else "")
        self.causa = causa  # opcional: guarda la excepción original


############################################################
############################################################
############################################################
## CLASE PARAMETROS DE INCIDENCIAS


class ParametrosIncidencias:
    def __init__(self, fichero_apps: str = "parametros/app.ini", fichero_prompts: str = "parametros/prompts.ini") -> None:
        """
        """
        # Diccionarios internos
        # Ejemplo de apps: {"app1": "aplicación 1", ...}
        self._apps: Dict[str, str] = {}

        # Ejemplo de prompts: {"app1": { "analiza_todas_incidencias": "...", ... }, ...}
        self._prompts: Dict[str, Dict[str, str]] = {}

        # Carga inicial
        self._loadApp(fichero_apps)
        self._loadPrompts(fichero_prompts)

    _clase="ParametrosIncidencias"

    # =========================
    # Métodos privados: Apps
    # =========================
    def _setApp(self, nombre_app: str, descripcion_app: str) -> None:
        """
        MÉTODO PRIVADO.
        Añade/actualiza una app en el diccionario interno de apps.
        Ej: _setApp("app1", "Aplicación 1")
        """
        method="_setApp"
        logging.debug(f"{self._clase}.{method}-START nombre_app={nombre_app} descripcion_app={descripcion_app}")
        self._apps[nombre_app] = descripcion_app

    def _getApp(self, nombre_app: str) -> str:
        """
        MÉTODO PRIVADO.
        Devuelve la descripción de una app concreta.
        Si la app no existe, lanza un KeyError.
        """
        method="_getApp"

        logging.debug(f"{self._clase}.{method}-START ombre_app={ombre_app}")

        if nombre_app not in self._apps:
            logging.error(f"{self._clase}.{method}-ERROR App {nombre_app} no encontrada en el diccionario de apps")
            raise KeyError(f"{self._clase}.{method}-ERROR La app '{nombre_app}' no existe en app.ini")
        return self._apps[nombre_app]

    # =========================
    # Métodos privados: Prompts
    # =========================
    def _setPrompt(self, nombre_app: str, tipo_prompt: PromptTipo, texto_prompt: str) -> None:
        """
        MÉTODO PRIVADO.
        Añade/actualiza un prompt para una app concreta.
        El tipo de prompt está restringido a PromptTipo.
        """
        method="_setPrompt"
        logging.debug(f"{self._clase}.{method}-START nombre_app={nombre_app}, tipo_prompt={tipo_prompt}, texto_prompt={texto_prompt}")

        if nombre_app!="generico" and nombre_app not in self._apps:
            logging.error(f"{self._clase}.{method}-ERROR App {nombre_app} no encontrada en el diccionario de apps")
            raise KeyError(f"{self._clase}.{method}-ERROR La app '{nombre_app}' no existe en app.ini")

        if nombre_app not in self._prompts:
            self._prompts[nombre_app] = {}
        self._prompts[nombre_app][tipo_prompt] = texto_prompt

    # =========================
    # Métodos privados: Carga de ficheros
    # =========================
    def _loadApp(self, ruta_fichero: str) -> None:
        """
        MÉTODO PRIVADO.
            Lee el fichero (una línea = un JSON) y carga las apps usando _setApp.

        FORMATO ESPERADO (JSON Lines):
            {"nombre_app":"aplicación 1", "descripcion_app":"descripcion 1", "servicenow_id":"asadkadalda"}
            {"nombre_app":"aplicación 2", "descripcion_app":"descripcion 2", "servicenow_id":"asadkadalda"}

        Es decir, cada línea debe ser un objeto JSON con las claves:
        - nombre_app (str)
        - descripcion_app (str)
        - servicenow_id (str)   # si no lo usas en _setApp, igualmente se valida/queda disponible
        """
        method = "_loadApp"
        logging.debug(f"{self._clase}.{method}-START Cargando apps desde fichero: {ruta_fichero}")

        if not os.path.exists(ruta_fichero):
            msg = f"{self._clase}.{method}-ERROR {ruta_fichero} no existe."
            raise IncidenciaException(msg)

        try:
            df = pd.read_json(ruta_fichero, lines=True)
        except ValueError as e:
            raise IncidenciaException(f"{self._clase}.{method}-ERROR JSON inválido en {ruta_fichero}", causa=e) from e

        logging.debug(f"{method}- Número app leídas son: {len(df)}")

        if df.empty:
            logging.debug(f"{self._clase}.{method}-INFO El fichero {ruta_fichero} está vacío. No se cargan apps.")
            return

        # Validación de columnas esperadas
        requeridas = {"nombre_app", "descripcion_app", "servicenow_id"}
        faltan = requeridas - set(df.columns)
        if faltan:
            raise IncidenciaException(
                f"{self._clase}.{method}-ERROR Formato inválido en {ruta_fichero}: faltan claves {sorted(faltan)}"
            )

        # Iteración por registros
        rows = df.to_dict(orient="records")

        for i, row in enumerate(rows, start=1):
            nombre_app = row.get("nombre_app")
            descripcion_app = row.get("descripcion_app")
            servicenow_id = row.get("servicenow_id")

            # Control de nulos/NaN y tipos
            if not isinstance(nombre_app, str) or not nombre_app.strip():
                raise IncidenciaException(f"{self._clase}.{method}-ERROR Línea {i}: 'nombre_app' debe ser string no vacío.")
            if not isinstance(descripcion_app, str) or not descripcion_app.strip():
                raise IncidenciaException(f"{self._clase}.{method}-ERROR Línea {i}: 'descripcion_app' debe ser string no vacío.")
            if not isinstance(servicenow_id, str) or not servicenow_id.strip():
                raise IncidenciaException(f"{self._clase}.{method}-ERROR Línea {i}: 'servicenow_id' debe ser string no vacío.")

            # Si tu _setApp NO acepta servicenow_id, lo ignoras (o lo guardas en otro sitio).
            # Si tu _setApp SÍ lo acepta, cambia a: self._setApp(nombre_app, descripcion_app, servicenow_id)
            self._setApp(nombre_app.strip(), descripcion_app.strip())

    def _loadPrompts(self, ruta_fichero: str) -> None:
        """
        MÉTODO PRIVADO.
        Lee el fichero prompts.ini (o el que se indique) y carga los prompts usando _setPrompt.

        FORMATO SOPORTADO (único formato):
        {
            "nombre_app": {
                "analiza_todas_incidencias": "....",
                "analiza_incidencia_causa_raiz": "....",
                "genera_propuestas": "....",
                "genera_prompt_app": "....",
                "calcula_descripcion_solucion": "...."
            },
            "generico": {
                ...
            }
        }

        - Las claves de primer nivel deben coincidir con las apps definidas en app.ini,
        EXCEPTO "generico", que se permite siempre.
        """
        method = "_loadPrompts"
        logging.debug(f"{self._clase}.{method}-START Cargando prompts desde fichero: {ruta_fichero}")

        if not os.path.exists(ruta_fichero):
            raise IncidenciaException(f"{self._clase}.{method}-ERROR {ruta_fichero} no existe.")

        # Leer JSON (un único objeto en todo el fichero)
        try:
            with open(ruta_fichero, "r", encoding="utf-8") as f:
                contenido = f.read().strip()
                if not contenido:
                    raise IncidenciaException(f"{self._clase}.{method}-INFO El fichero {ruta_fichero} está vacío. No se cargan prompts.")
                data = json.loads(contenido)
        except json.JSONDecodeError as e:
            raise IncidenciaException(f"{self._clase}.{method}-ERROR JSON inválido en {ruta_fichero}", causa=e) from e
        except OSError as e:
            raise IncidenciaException(f"{self._clase}.{method}-ERROR No se pudo leer {ruta_fichero}", causa=e) from e

        if not isinstance(data, dict):
            raise IncidenciaException(f"{self._clase}.{method}-ERROR El fichero {ruta_fichero} debe contener un único objeto JSON de nivel superior (dict).")

        # Validación dinámica coherente con PromptTipo
        tipos_permitidos: set[str] = set(PromptTipo.__args__)  # type: ignore[attr-defined]

        for nombre_app, prompts_app in data.items():
            logging.debug(f"{self._clase}.{method}- Procesando prompts para la app: {nombre_app}")

            if not isinstance(nombre_app, str):
                raise ValueError("Las claves de primer nivel en prompts.ini deben ser cadenas.")

            # Comprobamos que la app exista en _apps, pero permitimos 'generico'
            if self._apps and nombre_app != "generico" and nombre_app not in self._apps:
                msg=f"{self._clase}.{method} La app {nombre_app} en {ruta_fichero} no existe en el diccionario de apps y no es 'generico'"
                logging.debug(msg)
                raise ValueError(msg)

            if not isinstance(prompts_app, dict):
                raise ValueError(f"{self._clase}.{method}El valor de '{nombre_app}' en {ruta_fichero} debe ser un diccionario con los distintos tipos de prompt.")

            for tipo, texto in prompts_app.items():
                logging.debug(f"{self._clase}.{method}- Procesando tipo de prompt '%s' para app {tipo, nombre_app}")

                if not isinstance(tipo, str) or not isinstance(texto, str):
                    raise ValueError(f"{self._clase}.{method} En prompts.ini, para la app '{nombre_app}', cada clave de prompt y su valor deben ser cadenas.")

                if tipo not in tipos_permitidos:
                    raise ValueError(
                        f"Tipo de prompt '{tipo}' no permitido para la app '{nombre_app}'. "
                        f"Debe ser uno de: {sorted(tipos_permitidos)}"
                    )

                # Cast a PromptTipo para el type checker
                tipo_prompt_literal: PromptTipo = tipo  # type: ignore[assignment]
                self._setPrompt(nombre_app, tipo_prompt_literal, texto)



class Incidencias:
    _clase="Incidencias"

    def __init__(self, app:str, fichero_incidencias:str, fichero_apps: str = "parametros/app.ini", fichero_prompts: str = "parametros/prompts.ini", num_registros: int = None) -> None:
        """
        Constructor: inicializa diccionarios y carga apps y prompts desde los ficheros.

        Parametros:
            app (str): Nombre de la aplicación que vamos a procesar.
            fichero_incidencias (str): Ruta del fichero con incidencias.
            fichero_apps (str): Ruta del fichero de apps. Por defecto, "parametros/app.ini".
            fichero_prompts (str): Ruta del fichero de prompts. Por defecto, "parametros/prompts.ini".
            num_registros (int, optional): Número máximo de registros a leer del Excel.
                Si es None o None, se leen todos los registros. Si es un número positivo,
                se leen como máximo ese número de registros (útil para pruebas con grandes ficheros).
        """
        method="___init___"

        logging.debug(f"{self._clase}.{method}-START Incidencias con fichero_apps={fichero_apps}, fichero_prompts={fichero_prompts}, num_registros={num_registros}")

         # ----
         # Inicialización de variables internas
         # ----

         #Nombre de la App que vamos a procesar.

         # Nombre del fichero con incidencias y App que va a gestioanr.
         # Preparamos para que si el fichero de incidencias no acaba en .xls se lo añadimos para mayor flexibilidad.
        self._app_name = app
        self._fichero_incidencias = fichero_incidencias if fichero_incidencias.lower().endswith(".xlsx") else f"{fichero_incidencias}.xlsx"
        self._num_registros = num_registros  # Guardar el número de registros a leer

        if not os.path.exists(self._fichero_incidencias):
            raise IncidenciaException(f"{self._clase}.{method}-ERROR No existe el fichero {self._fichero_incidencias}")

        logging.debug(f"{self._clase}.{method}- Inicializado para {self._app_name} y fichero {self._fichero_incidencias}")

         #Parámetros de carga de las apps soportadas y de los prompts soportados.
        parametros = ParametrosIncidencias(fichero_apps=fichero_apps, fichero_prompts=fichero_prompts)
        self._apps = parametros._apps
        self._prompts = parametros._prompts

         #Cargamos las incidencias.
        self._df = self._loadIncidencias(num_registros=num_registros)

        #Preparamos el diccionario para tener los dfs de cada modelo, en caso se usen con una lista de modelos.
        self._df_modelos = {}

        #Por defecto, timeout de 5 minutos.
        self._timeout=300.0

    # =========================
    # Métodos Auxiliares
    # =========================

    def _get_tokens(self, prompt:str):
        palabras = prompt.split()
        tokens=math.ceil(len(palabras)*1.35)

        return palabras, tokens

    def _renderiza_prompt(self, row, lista_variables: list, lista_campos:list, prompt: str) -> str:
        ctx = {}
        for var, col in zip(lista_variables, lista_campos):
            val = row[col]
            if pd.isna(val):
                val = ""
            ctx[var] = val

        return prompt.format_map(ctx)

    def _ejecuta_prompts(self, prompt:str, model:str):
        method="_ejecutaPrompts"

        system = '''
            You are an expert analist in detecting the root cause for incidents in the department of micro computer.
            You works for a very big company first of its class.
            You are the best detecting root cause and proposing viable solutions.
            You have a reward of 2.000.000$ for reducing number of incidents with your solutions.
            If cant make proposals, you are fired.
            The only lenguage you can answered is spanish whatever language you can find in the incidents.
        '''

        palabras, num_tokens = self._get_tokens(prompt)
        logging.debug(f"{method}-START ejecutando modelo {model}, temperatura={self._temperature} para el prompt={prompt}, timeout={self._timeout}")

        resp = ollama_manager.call_ollama_api(model=model, system_message=system, user_message=prompt, temperature=self._temperature, timeout=self._timeout)
        resp = resp.lower().replace("json", '').replace("```", '')
        content, cot = ollama_manager.separa_thinking_contenido(resp)

        return content, cot, num_tokens


    def _ejecutarAnalisisGeneral(self, model:str, listado_json:list, prompt:str, sufix_file:str):
        """
        The function `_ejecutarAnalisisGeneral` is a helper function that calls the LLM with the incident description / solution. The steps are:
        - Invoking LLM
        - Saving all the response in file. The file is the original file + sufix with the model and the execution. Sufix is already calculated in the invocation.

        Parameters:
            model:str --> Modelo actual.
            listado_json:list --> Lista con los objetos de json.
            prompt:str --> Prompt, que lleva dos variables, listado_json y app.
            sufix_file:str --> Sufijo del fichero que vamos a generar de forma individuall.

        Exception:
            None.

        Return:
            llm_ouput: str --> Análisis del LLM. No considera la cadena de thinking.
        """
        method="_ejecutarAnalisisGeneral"

        #2.- Miramos si el fichero está creado.
        fichero_ouput=f"{self._fichero_incidencias.replace('.xlsx','')}_{sufix_file}.txt"

        #Si ya existe no hacemos nada.
        if os.path.exists(fichero_ouput):
            logging.info(f"{self._clase}.{method}-START fichero {fichero_ouput} ya existe, no se genera.")

            with open(fichero_ouput, "r",  encoding="utf-8") as f:
                todo = f.read()
                todo = todo.lstrip("\ufeff")  # por si hay BOM
                m = re.match(r"^\s*<think>.*?</think>\s*", todo, flags=re.DOTALL | re.IGNORECASE)

                salida = todo[m.end():] if m else todo
                logging.debug(f"{self._clase}.{method}- salida recuperada={salida}")
        else:
            #2.- Ejecutamos el prompt
            json_object = {"analisis_list": listado_json}
            json_output = json.dumps(json_object, indent=2)

            prompt_real=prompt.format(listado_json=str(json_output), app=self._app_name, numero_incidentes=len(listado_json))
            content, cot, num_tokens = self._ejecuta_prompts(prompt_real, model)

            #Convertimos salida en texto, y cambiamos el \n por \r\n.
            salida_cot = f"{cot}".replace('\r\n', '\n').replace('\r', '\n').replace('\\n', '\n')
            salida = f"{content}".replace('\r\n', '\n').replace('\r', '\n').replace('\\n', '\n')

            #Genera un archivo de salida Excel con el nombre del modelo, reemplazando el : por _.
            with open(fichero_ouput, "w",  encoding="utf-8") as f:
                f.write(f"<think>\n{salida_cot}\n</think>\n{salida}")
            logging.info(f"{method}-END fichero {fichero_ouput} generado.")

        return fichero_ouput, salida

    def _obtenerDatosIncidencias(self, df_proceso: pd.DataFrame, numero_elemento_inicial: int, context_size: int, lista_campos_variables: list, margen=0.9):
        """
        The function `_obtenerDatosIncidencias` is a helper function that processes the DataFrame e prepares the list
        of json elements to send the LLM. It considers not preparing more elements that those can enter in the
        context window we already have.

        Parameters:
            df_proceso: pd.DataFrame --> DataFrame con los datos de incidencias
            numero_elemento_inicial:int --> Número del primer elemento a procesar
            context_size:int --> Tamaño máximo de contexto
            lista_campos_variables:list --> Lista de campos a incluir en el JSON
            margen:numeric --> Margen que queremos mantener para asegurar que no nos pasamos del contexto. Por defecto, 0.9

        Exception:
            None.

        Return:
            numero_elemento_final --> last element processed
            lista_objetos_json --> processed json element.
        """
        method="_obtenerDatosIncidencias"

        lista_objetos_json = []
        numero_elemento_actual = numero_elemento_inicial
        tokens_totales = 0
        limite_tokens = int(context_size * margen)  # 10% de margen
        continuar = True

        logging.debug(f"{self._clase}.{method}-START Entrando con={numero_elemento_inicial} / {len(df_proceso)-1}, context_size={context_size}")

        while numero_elemento_actual < len(df_proceso) and continuar:
            # Recuperar una fila del dataframe
            row = df_proceso.iloc[numero_elemento_actual]

            # Crear objeto JSON con los campos especificados
            objeto_json = {}
            objeto_json["id"] = row.iloc[0]
            for campo in lista_campos_variables:
                objeto_json[campo] = row.get(campo, "")

            # Verificar la longitud en tokens
            _, tokens_row = self._get_tokens(str(objeto_json))
            logging.debug(f"{self._clase}.{method}- Elemento={numero_elemento_actual}-Id={row.iloc[0]}, tokens={tokens_row}, aggregado={tokens_totales}")

            # Verificar si se puede agregar el elemento
            if tokens_totales + tokens_row <= limite_tokens:
                lista_objetos_json.append(objeto_json)
                tokens_totales += tokens_row
                numero_elemento_actual += 1
            else:
                # Salir del bucle si excede el límite
                continuar = False

        return numero_elemento_actual, lista_objetos_json

    # =========================
    # Métodos Privados
    # =========================

    def _loadIncidencias(self, lista_campos = LISTA_CAMPOS_SPAGNA, num_registros: int = None):
        """
        Lee un archivo de incidencias Excel y se queda solo con el listado de campos que se especifican.

        Este debe ser el orden de los campos.

        Sólo da libertad para poder cargar diferentes excels que tengan nombre de campos distintos de forma paramétrica.

        Parametros:
             - lista_campos: Lista de campos que se quieren extraer del archivo Excel. Por defecto, se extraen los campos "Número", "Descripción corta" y "Notas de resolución".
             - num_registros: Número máximo de registros a leer. Si es None, se leen todos.

        Return:
            Un DataFrame con los campos especificados extraídos del archivo Excel, limitado a num_registros si se especifica.
        """
        method ="_loadIncidencias"

        file_name_path = self._fichero_incidencias
        logging.info(f"{self._clase}.{method}-START - Leyendo el archivo Excel: {file_name_path}")

        df = pd.read_excel(file_name_path, index_col=None)
        logging.info(f"{self._clase}.{method}- {df.shape[0]} registros leídos en total.")

         # Limitar el número de registros si se especifica num_registros
        if num_registros is not None and num_registros > 0:
            df = df.head(num_registros)
            logging.info(f"{self._clase}.{method}- Limitando a {num_registros} registros.")

        #Copia y selección de los tres campos que necesitamos.
        df_filtrado = df.copy()
        #df_filtrado = df_filtrado[lista_campos]
        df_filtrado.columns = df_filtrado.columns.str.lower()
        #df_filtrado.rename(columns={lista_campos[0].lower(): "id"
             #                     , lista_campos[1].lower(): "desc"
             #                     , lista_campos[2].lower(): "res"
             #                     }, inplace=True)

        logging.debug(f"{self._clase}.{method}-END - Se ha filtrado el DataFrame para obtener los campos especificados: {df_filtrado.columns}")

        return df_filtrado

    ##
    ## Necesarios para trabajar con los DFs de cada modelo.
    ##

    def _setDf(self, modelo:str, df: pd.DataFrame) -> None:
        """
        Asigna un df en el diccionario de dfs para cada modelo.

        :param self: Descripción
        :param modelo: el nombre del modelo de ia.
        """
        method="_setDf"
        self._df_modelos[modelo] = df

    def _getDf(self, modelo:str) -> pd.DataFrame:
        """
        Recupera el df de un modelo.

        :param self: Descripción
        :param modelo: nombre del modelo
        :return: Datos del Df que se han procesado con ese modelo, o None en caso contrario.
        :rtype: DataFrame
        """
        method="_getDf"

        df = self._df_modelos.get(modelo)
        df_return = None
        if df is None:
            logging.debug(f"{method}-ERROR no se ha procesado aún datos para el modelo {modelo}")
        else:
            df_return = df.copy()

        return df_return
    ##
    ## Necesarios para trabajar con promts.
    ##

    def _getPrompt(self, nombre_app: str, tipo_prompt: str) -> str:
        """
        MÉTODO PRIVADO.
        Devuelve el texto de un prompt para una app y tipo de prompt concreto.
        - nombre_app: clave de la app (por ejemplo, "app1")
        - tipo_prompt: uno de los valores de PromptTipo

        Comportamiento:
        1) Intenta recuperar el prompt específico de la app.
        2) Si no existe, intenta recuperar el prompt de la app 'generico'.
        3) Si tampoco existe, lanza KeyError.
        """
        method="_getPrompt"
        logging.debug(f"{self._clase}.{method}-START nombre_app={nombre_app}, tipo_prompt={tipo_prompt}")

        prompt=None
        # 1) Buscar prompt específico de la app
        if nombre_app in self._prompts:
            prompts_app = self._prompts[nombre_app]
            if tipo_prompt in prompts_app:
                logging.debug(f"{self._clase}.{method} Encontrado prompt específico para app {nombre_app} y tipoPromtp={tipo_prompt}")
                prompt=prompts_app[tipo_prompt]

        # 2) Fallback a la app genérica
        if prompt is None and "generico" in self._prompts:  # <-- CAMBIO generico
            logging.debug(f"{self._clase}.{method}- Cambiando a genérico para app={nombre_app} y tipoPrompt={tipo_prompt}")
            prompts_generico = self._prompts["generico"]
            if tipo_prompt in prompts_generico:
                logging.info(f"{self._clase}.{method}- Encontrado.")
                prompt=prompts_generico[tipo_prompt]

        # 3) Error si no existe ni específico ni genérico
        if prompt is None:
            msg =f"{self._clase}.{method}-ERROR No existe para app {nombre_app} el tipoPrompt={tipo_prompt} ni en la app 'generico'"
            logging.error(msg)
            raise KeyError(msg)

        return prompt

    ##
    ## Necesarios para procesar el excel
    ##

    def _addColumns(self, df_nuevo, sufijo, fichero_output_path, model, prompt, lista_variables, lista_campos):
        """
        Agrega columnas a un DataFrame llamado df con las causas raíz y clasificaciones obtenidas por el modelo Ollama.

        Parametros:
            df (pandas.DataFrame): El DataFrame que contiene las descripciones y notas de resolución.
            sufijo (str) : Sufijo para las columnas de status y cot porque puede haber diversos prompts que creen información extra en el excel.
            fichero_output_path (str): Nombre del fichero sobre el cual se está grabando cada 20 iteracciones.
            model (str): El nombre del modelo Ollama a usar para obtener las causas raíz y clasificaciones. Por defecto, es "gemma3:latest".
            prompt (str): Prompt que se va a ejecutar.

        Return:
            Una copia del data frame original con las nuevas columnas para todas las incidencias.
        """
        method="add_columns"

        logging.info(f"{method}-START iniciando generación información para {df_nuevo.shape[0]} registos con el modelo {model} y cot {self._thinking}")
        logging.debug(f"{method}- lista_variables:{lista_variables}, lista_campos:{lista_campos}")

        generado=0
        logging.debug(f"{method}- columnas del DF: {df_nuevo.columns}")
        for index, row in df_nuevo.iterrows():
            #Generamos un bucle para calcular en tiempo de ejecución
            prompt_modificado =  self._renderiza_prompt(row, lista_variables, lista_campos, prompt)

            status = row[f'status_{sufijo}']

            #Sólo procesamos los datos con la IA si no están ya generados.
            if status != 'OK':
                #Bucle para volver a pedir cuando haya un problema en el token devuelto.
                while status != "OK":
                    content, cot, num_tokens = self._ejecuta_prompts(prompt_modificado, model)
                    logging.info(f"{method}- Index={index}, ID = {row.iloc[0]} con {num_tokens} tokens --> output={content}")
                    logging.debug(f"{method}- Index={index}, Longitud CoT={len(cot)}, longitud Content={len(content)}")

                    try:
                        contenido = json.loads(content)
                        logging.debug(f"{method}- generado contenido={contenido}")

                        #Procesamos el json para meter de forma dinámica las columnas.
                        num=0
                        for key, value in contenido.items():
                            col = key.lower()

                            # crea la columna si no existe (opcional; pandas la crea igualmente al asignar)
                            if col not in df_nuevo.columns:
                                df_nuevo[col] = None

                            df_nuevo.at[index, col] = value
                            num+=1

                        logging.debug(f"{method}- procesados {num} campos")

                        df_nuevo.at[index, f'cot_{sufijo}'] = cot[:30000]
                        df_nuevo.at[index, f'status_{sufijo}'] = "OK"

                        #MArcamos la opción de salir del while.
                        status = 'OK'
                    except Exception as e:
                        logging.error(f"{method}-ERROR al parsear JSON (ID={row.iloc[0]}) con error {e}")
                        df_nuevo.at[index, f'status_{sufijo}'] = "ERROR"

                #Cada 50 interacciones guardamos el fichero para ir manteniendo el progreso.
                generado+=1
                if generado % 20 == 0:
                    df_nuevo.to_excel(fichero_output_path, index=False)
                    logging.info(f"{method}- Guardando archivo Excel en {fichero_output_path}")

            else:
                logging.debug(f"{method}- Index={index}, Status = OK para el id {row.iloc[0]}")


        return df_nuevo

    def _procesaIncidencias(self, df, sufijo, model, prompt, lista_variables, lista_campos):
        """
        Procesa las incidencias una a una. Recibe un prompt que generará un json. Se debe procesar el prompt
        para guardar los campos del json en el dataframe.

        """
        method="procesa_incidencias"

        #Preparamos el nombre del modelo.
        model_name = model.replace(':', '_')

        #Generamos el nombre del fichero de salida.
        fichero_ouput_path=f"{self._fichero_incidencias.replace('.xlsx','')}_{model_name}.xlsx"

        #Si el fichero existe, lo cargamos en vez de procesar los datos que nos llegan.
        #Si no, procesamos los datos que nos llegan.
        if os.path.exists(fichero_ouput_path):
            df_nuevo = pd.read_excel(fichero_ouput_path, index_col=None)
            logging.info(f"{method}-START Fichero {fichero_ouput_path} ya existente. Se ha leído.")
        else:
            df_nuevo = df
            logging.info(f"{method}-START Procesando por primera vez al no existir {fichero_ouput_path}.")

        #Procesa cada incidencia.
        df_nuevo = self._addColumns(df_nuevo, sufijo, fichero_ouput_path, model, prompt, lista_variables, lista_campos)

        #Genera un archivo de salida Excel con el nombre del modelo, reemplazando el : por _.
        df_nuevo.to_excel(fichero_ouput_path, index=False)
        self._setDf(model_name, df_nuevo.copy())

        logging.info(f"{method}- Archivo de salida generado: {fichero_ouput_path}")

        return df_nuevo

    def _consolidaAnalisisGeneral(self, model, fichero_ouput:str, lista_ficheros:list, lista_analisis:list) -> str:
        """
        La función `_consolidaAnalisisGeneral` consolida en un único fichero todas las causas raices que se han analizado
        respetando la ventana de contexto existente.

        Parámetros:
            - fichero_output: str --> fichero donde se debe consolidar todos los ficheros que se han generado.
            - lista_ficheros: list --> Lista de ficheros que se han generado.
            - salida: list --> Lista de contenidos que se han generado.

        Exception:
            None

        Return:
            - salida: str --> La salida que se ha consolidado.
        """
        method="_consolidaAnalisisGeneral"

        logging.info(f"{self._clase}.{method}-START consolidando todos los análisis (un total de {len(lista_analisis)})")

        #Si hemos tenido que ejecutar más de 1 vez, tenemos que resumir
        if len(lista_analisis) > 1:
            #consolidamos los ficheros que se han generado. Se crea un nuevo fichero y se borran el resto.
            json_dict = {f"exec_{i}": var for i, var in enumerate(lista_analisis)}
            json_output = json.dumps(json_dict)

            #Recuperamos prompt y ejecutamos.
            prompt = self._getPrompt(self._app_name, PROMPT_CONSOLIDA_ANALISIS_GENERAL)
            prompt_with_data = prompt.format(json_output=json_output)
            content = ollama_manager.call_ollama_api(model, "", prompt_with_data)

            #grabamos a disco
            with open(fichero_ouput, "w",  encoding="utf-8") as f:
                f.write(content)

            #eliminamos los fihceros temporales.
            """
            for file in lista_ficheros:
                try:
                    os.remove(file)
                    logging.debug(f"{self._clase}.{method}: Borrando {file}")
                except FileNotFoundError:
                    logging.debug(f"{self._clase}.{method}: No se encuentra {file}")
                except PermissionError:
                    logging.debug(f"{self._clase}.{method}: Permiso denegado al borrar {file}")
            """
        else:
            #Tenemos que renombar el fichero sin el ejecución_1
            fichero_origen=f"{self._fichero_incidencias.replace('.xlsx','')}_{model.replace(':', '_')}_ejecucion_1.txt"
            os.rename(fichero_origen, fichero_ouput)


    # =========================
    # Métodos Públicos
    # =========================

    def setModeloEntreFases(self, modelo:str):
        method="setModeloEntreFases"
        logging.info(f"{modelo}-START Asignado intra modelo {modelo} para los modelos configurados {self._modelos}")
        if modelo not in self._modelos:
            raise IncidenciaException(f"{method}-ERROR este modelo no está configurado en los modelos actuales.")
        self._modelo_entre_modelos = modelo

    def setDatosModelos(self, modelos:list, temperature: float, flg_thinking:bool) -> None:
        self._modelos=modelos
        self._temperature = temperature
        self._thinking = flg_thinking

    def setTimeout(self, timeout=int):
        self._timeout = timeout

    def getApps(self):
        return list(self._apps.keys())

    #######
    # USO DE LLM
    #######

    #######
    # Métodos que tratan el total de las incidencias, si permite el contexto.

    def analiza_todas_incidencias(self, context_size:int) -> None:
        """
        The function `analiza_todas_incidencias` is the second method to use in the workflow of incident analysis.

        It uses the already calculated desc, res fields to generates a first global classification of the incidents for a given application.

        It has the following considerations:
        - Only processes incidents that are already closed, so it can have description and also solutions informed.
        - it considers the context size given, so it sends to llm information only considering the context window.
        - If it has been to make more than one call to the llm, it makes a new call to consolidate all classifications into one only file.

        Parameters:
            context_size:integer --> The name of the fields that we need use from the data frame loaded. First. field must be the ID for logging reasons.

        Exception:
            Raises an IncidenException if validations are not superated. Size of context_size, it hasn't be assigned the models, etc.

        Return:
            None
        """
        method="analiza_todas_incidencias"
        logging.info(f"{self._clase}.{method}--------------------------------------------------------------")
        logging.info(f"{self._clase}.{method}-START Inicio análisis y clasificación general de incidencias.")
        logging.info(f"{self._clase}.{method}- Análisis general sobre el dataframe.")
        logging.info(f"{self._clase}.{method}- modelos a usar: {self._modelos}, razonamiento para modelos generales: {self._thinking}")
        logging.info(f"{self._clase}.{method}- temperatura: {self._temperature}, aplicación: {self._app_name}")
        logging.info(f"{self._clase}.{method}--------------------------------------------------------------")

        prompt = self._getPrompt(self._app_name, PROMPT_ANALIZA_TODAS)
        logging.debug(f"{self._clase}.{method}- Prompt a usar: ")

        ###
        #Validamos que recibimos todos los campos y preparamos la lista de campos que están en el prompt
        #Estas variables se tienen que generar en tiempo de ejecución para cada incidencia, por eso se tienen que pasar al método _procesaIncidencia.
        if context_size < 2028 :
            raise IncidenciaException(f"{method}-ERROR Tamaño de contexto insuficiente.")

        if self._modelos is None:
            raise IncidenciaException(f"{method}-ERROR No se han especificado los modelos a usar.")
        ###

        #Partimos del último modelo generado.
        model = self._modelo_entre_modelos
        df_proceso = self._getDf(model)
        if df_proceso is None:
            raise IncidenciaException(f"{method}-ERROR El modelo {model} no ha sido usado para generar las variables `desc` con el resumen de descripción y `res` con el resumen de resolución.")

        logging.info(f"{self._clase}.{method}-START usando datos del modelo {model}")
        lista_campos_variables=["desc", "res"]
        lista_salida = []

        for model in self._modelos:
            logging.info(f"{self._clase}.{method}- iniciando proceso para el modelo {model}")

            #Copiamos el DF.
            numero_elemento = -1
            ejecuciones = 0
            lista_analisis = []
            lista_ficheros = []

            #Si ya está creado el fichero, no lo procesamos el fichero.
            fichero_ouput=f"{self._fichero_incidencias.replace('.xlsx','')}_{model.replace(':', '_')}.txt"

            if os.path.exists(fichero_ouput):
                logging.info(f"{self._clase}.{method}- ya existe el fichero {fichero_ouput} para el modelo {model}.")
                with open(fichero_ouput, "r",  encoding="utf-8") as f:
                    todo = f.read()
                    todo = todo.lstrip("\ufeff")  # por si hay BOM
                    m = re.match(r"^\s*<think>.*?</think>\s*", todo, flags=re.DOTALL | re.IGNORECASE)
                    salida = todo[m.end():] if m else todo
                    logging.debug(f"{self._clase}.{method}- salida recuperada={salida}")
                    lista_salida.append(salida)
                continue

            #Vamos procesando en bloques de context_size.
            while numero_elemento < len(df_proceso):
                ejecuciones+=1
                numero_elemento, listado_json = self._obtenerDatosIncidencias(df_proceso, numero_elemento+1, context_size, lista_campos_variables)
                _, tokens = self._get_tokens(str(listado_json))
                logging.info(f"{self._clase}.{method}-  Ejecucion={ejecuciones}, procesando {numero_elemento}/{len(df_proceso)} elementos con un total de {tokens} tokens.")
                #logging.info(f"{self._clase}.{method}-  Último código de incidencia {df_proceso.iloc[numero_elemento][0]}")

                sufix_file = model.replace(':', '_') + "_" + f"ejecucion_{ejecuciones}"
                fichero_ejecucion_output, salida = self._ejecutarAnalisisGeneral(model, listado_json, prompt, sufix_file)
                logging.info(f"{self._clase}.{method}-  Ejecucion {ejecuciones} finalizada.")

                lista_analisis.append(salida)
                lista_ficheros.append(fichero_ejecucion_output)

            salida = self._consolidaAnalisisGeneral(model, fichero_ouput, lista_ficheros, lista_analisis)
            lista_salida.append(salida)

        logging.info(f"{self._clase}.{method}-end Fin de proceso para el modelo {model}")

        logging.info(f"{self._clase}.{method}---------------------------------------------------")
        logging.info(f"{self._clase}.{method} END")
        logging.info(f"{self._clase}.{method}---------------------------------------------------")

        return lista_salida

    def genera_propuestas(self, modelos:list) -> None:
        """
        Genera propuestas de solución para una incidencia.
        (De momento sin implementar)
        """
        logging.info(
            "Llamada a genera_propuestas(incidencia=%s) (no implementado)",
            incidencia,
        )
        pass

    def genera_prompt_app(self, model:str, modelo_generador_prompt:str="qwen3:30b-a3b-thinking-2507-q4_K_M") -> str:
        """
        Genera el prompt específico para una app dado un contexto de incidencia.
        (De momento sin implementar)
        """
        method="genera_prompt_app"
        logging.info(f"{self._clase}.{method}-----------------------------------------------------")
        logging.info(f"{self._clase}.{method}-START Inicio de causa raíz, clasificación y solución")
        logging.info(f"{self._clase}.{method}- Análisis incidencia a incidencia.")
        logging.info(f"{self._clase}.{method}- modelo que se recupera: {model} , usando modelo generador {modelo_generador_prompt}")
        logging.info(f"{self._clase}.{method}- temperatura: {self._temperature}, aplicación: {self._app_name}")
        logging.info(f"{self._clase}.{method}-----------------------------------------------------")

        #1. Conseguimos prompt para generar el prompt.
        prompt = self._getPrompt(self._app_name, PROMPT_GENERA_PROMPT)

        #2. Recuperamos la información del fichero para el modelo que se indica.
        model_name = model.replace(':', '_')
        fichero_input_path=f"{self._fichero_incidencias.replace('.xlsx','')}_{model_name}.xlsx"

        with open(fichero_input_path, "r", encoding="utf-8") as f:
            content = f.read()

        analisis_incidencias, cot = ollama_manager.separa_thinking_contenido(content)
        prompt_formateado=prompt.replace("{analisis_incidencias}", analisis_incidencias)

        salida = ollama_manager.call_ollama_api(modelo_generador_prompt, "", prompt_formateado)
        content, thinking = ollama_manager.separa_thinking_contenido(salida)

        logging.info(f"{self._clase}.{method}---------------------------------------------------")
        logging.info(f"{self._clase}.{method} END")
        logging.info(f"{self._clase}.{method}---------------------------------------------------")

        return content

    #######
    # Métodos que van a iterar para todas las incidenicas.

    def analiza_incidencia_causa_raiz(self, lista_campos:list, fichero_output=None) -> None:
        """
        The function `analiza_incidencia_causa_raiz` is the third method to use in the workflow of incident analysis.

        It performs for every model given, an llm analisi to generate a specific classification, resolution and root casuse of the incident.

        It saves all the information generated in a file (using original name + sufix with the model name), and also,
        saves the DataFrame processed in an internal dictionary name.

        The DataFframe processed is the original + three new fields:
        - classification --> Description resume of the incident.
        - rootcause --> A brief description of the rootcause
        - solution --> Solution made in the ticket.

        Also, are added another three fields:
        - status --> to know if it has benn processed or not,
        - cot --> The Chain of Thought returned by the model,
        - model --> The model used to generate the information.

        Parameters:
            lista_campos:list --> The name of the fields that we need use from the data frame loaded. First. field must be the ID for logging reasons.

        Exception:
            Raises an IncidenException if validations are not superated. The lista_campos fields has not all elements, it hasn't be assigned the models, etc.

        Return:
            None
        """
        method="analiza_incidencia_causa_raiz"
        logging.info(f"{self._clase}.{method}-----------------------------------------------------")
        logging.info(f"{self._clase}.{method}-START Inicio de causa raíz, clasificación y solución")
        logging.info(f"{self._clase}.{method}- Análisis incidencia a incidencia.")
        logging.info(f"{self._clase}.{method}- modelos a usar: {self._modelos}, razonamiento para modelos generales: {self._thinking}")
        logging.info(f"{self._clase}.{method}- temperatura: {self._temperature}, aplicación: {self._app_name}")
        logging.info(f"{self._clase}.{method}-----------------------------------------------------")

        #Recuperamos el promtp. Si no se encuentra en la lista de prompts, calculamos uno y lo guardamos en fichero.
        try:
            existe_prompt = True
            prompt = self._getPrompt(self._app_name, PROMPT_ANALIZA_CAUSA_RAIZ)
            logging.debug(f"{self._clase}.{method}- Prompt a usar existente: {prompt}")
        except Exception as e:
            #Si salta excepción es que no tenemos prompt y lo tenemos que calcular.
            existe_prompt = False

        sufijo = "cr"

        #Validamos que recibimos todos los campos y preparamos la lista de campos que están en el prompt
        #Estas variables se tienen que generar en tiempo de ejecución para cada incidencia, por eso se tienen que pasar al método _procesaIncidencia.
        if len(lista_campos) != 3 :
            raise IncidenciaException(f"{method}-ERROR La lista de campos no tiene los 2 elementos necesarios: desc, res.")

        lista_variables = ["desc", "res", "ticket_type"]

        #Iteramos para cada modelo
        for model in self._modelos:
            logging.info(f"{self._clase}.{method}-start Inicio de proceso para el modelo {model}")
            model_name = model.replace(':', '_')

            #Si no existe prompt lo generamos y lo guardamos en fichero.
            if existe_prompt == False:
                logging.info(f"{self._clase}.{method}- calculando prompt porque no existe analisis causa raíz para la app {self._app_name}")
                prompt = self.genera_prompt_app(model)

                fichero_output = f"{self._fichero_incidencias.replace('.xlsx','')}_prompt_CR_{model_name}.txt"
                with open(fichero_output, "w") as f:
                    f.write(prompt)
            else:
                logging.info(f"{self._clase}.{method}- Prompt recuperado")

            #Copiamos el DF.
            df_proceso = self._getDf(model_name)
            df_nuevo = None
            if df_proceso is None:
                logging.debug(f"{method}- Columnas recuperadas: {df_proceso.columns}")
                df_nuevo = df_proceso.copy()
                df_nuevo[f'status_{sufijo}'] = "PEND"
                df_nuevo[f'cot_{sufijo}'] = "'"
                df_nuevo[f'model{sufijo}'] = model
                logging.debug(f"{method}- Columnas actualizadas: {df_nuevo.columns}")

                #Grabamos el Excel para meter las columnas nuevas.
                fichero_ouput_path=f"{self._fichero_incidencias.replace('.xlsx','')}_{model_name}.xlsx"
                df_nuevo.to_excel(fichero_ouput_path, index=False)
            else:
                logging.error(f"{method}-ERROR no hay df_proceso")

            #Procesamos el DF completo, sabiendo que es posible que esté realizado.
            self._procesaIncidencias(df_nuevo, sufijo, model, prompt, lista_variables, lista_campos)
            logging.info(f"{self._clase}.{method}-end Fin de proceso para el modelo {model}")


        logging.info(f"{self._clase}.{method}---------------------------------------------------")
        logging.info(f"{self._clase}.{method} END")
        logging.info(f"{self._clase}.{method}---------------------------------------------------")

    def calcula_descripcion_solucion(self, lista_campos:list, lista_variables = None) -> None:
        """
        The function `calcula_descripcion_solucion` is the first method to use in the workflow of incident analysis.

        It performs for every model given, an llm analisi to generate a specific resume of the incident description and the
        solution description.

        It saves all the information generated in a file (using original name + sufix with the model name), and also,
        saves the DataFrame processed in an internal dictionary name.

        The DataFframe processed is the original + three new fields:
        - desc --> Description resume of the incident.
        - res --> Incident Solution resumen.
        - res_type --> Type of resolution generated: real (means the incident has a real resolution included), estimated (means the incident doesn't have included a real resolution)

        Also, are added another three fields:
        - status --> to know if it has benn processed or not,
        - cot --> The Chain of Thought returned by the model,
        - model --> The model used to generate the information.

        Parameters:
            lista_campos:list --> The name of the fields that we need use from the data frame loaded. First. field must be the ID for logging reasons.

        Exception:
            Raises an IncidenException if validations are not superated. The lista_campos fields has not all elements, it hasn't be assigned the models, etc.

        Return:
            None
        """
        method="calcula_descripcion_solucion"
        logging.info(f"{self._clase}.{method}---------------------------------------------")
        logging.info(f"{self._clase}.{method}-START Inicio cálculo Descripción y Solución.")
        logging.info(f"{self._clase}.{method}- Análisis incidencia a incidencia.")
        logging.info(f"{self._clase}.{method}- modelos a usar: {self._modelos}, razonamiento para modelos generales: {self._thinking}")
        logging.info(f"{self._clase}.{method}- temperatura: {self._temperature}, aplicación: {self._app_name}")
        logging.info(f"{self._clase}.{method}---------------------------------------------")

        prompt = self._getPrompt(self._app_name, PROMPT_GENERA_DESC_SOL)
        logging.debug(f"{self._clase}.{method}- Prompt a usar: ")

        sufijo = "cds"

        ###
        #Validamos que recibimos todos los campos y preparamos la lista de campos que están en el prompt
        #Estas variables se tienen que generar en tiempo de ejecución para cada incidencia, por eso se tienen que pasar al método _procesaIncidencia.
        if len(lista_campos) < 6 :
            raise IncidenciaException(f"{method}-ERROR La lista de campos no tiene los 6 elementos necesarios: id, descripcion, descripcion corta, nota resolución, nota de trabajo, estado.")

        if self._modelos is None:
            raise IncidenciaException(f"{method}-ERROR No se han especificado los modelos a usar.")
        ###
        if lista_variables is None:
            lista_variables = ["id", "description", "descripcion_corta", "nota_resolucion", "nota_trabajo", "comentario_nota_trabajo", "estado", "app_name"]

        #Iteramos para cada modelo
        for model in self._modelos:
            logging.info(f"{self._clase}.{method}-start Inicio de proceso para el modelo {model}")

            model_name = model.replace(':', '_')

            #Copiamos el DF.
            df_proceso = self._getDf(model_name)
            if df_proceso is None:
                df_proceso = self._df.copy()
                df_proceso[f'status_{sufijo}'] = "PEND"
                df_proceso[f'cot_{sufijo}'] = ""
                df_proceso[f'model{sufijo}'] = model

            #Procesamos el DF completo, sabiendo que es posible que esté realizado.
            df_local = self._procesaIncidencias(df_proceso, sufijo, model, prompt, lista_variables, lista_campos)
            self._setDf(model, df_local)
            logging.info(f"{self._clase}.{method}-end Fin de proceso para el modelo {model}")

        logging.info(f"{self._clase}.{method}---------------------------------------------------")
        logging.info(f"{self._clase}.{method} END")
        logging.info(f"{self._clase}.{method}---------------------------------------------------")