
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: transcribe/extrae_pdf.ipynb

import logging
import fitz
import re
import io
from typing import Tuple
from PIL import Image
import unicodedata
from docx import Document
from mlx_vlm import load, generate
from mlx_vlm.prompt_utils import apply_chat_template

import sys
from pathlib import Path

class PDFTranscriber:
    _class_name = "PDFTranscriber"

    DEFAULT_PROMPT = """
    Transcribe esta página de forma literal y completa.

    #Instrucciones:
    - Devuelve únicamente la transcripción.
    - Mantén el orden de lectura natural, empezando de izquierda a derecha y de arriba a abajo.
    - Conserva títulos, párrafos, listas, tablas simples y saltos de línea razonables.
    - No resumas.
    - No expliques nada.
    - No corrijas el contenido.
    - No añadas texto que no esté en la imagen.
    - Si hay texto dudoso, escribe la mejor lectura posible.
    - Si una zona es ilegible, marca solo esa zona como [ilegible].
    """

    DEFAULT_MODEL = "mlx-community/Qwen3.5-35B-A3B-4bit"
    OLD_MODEL = "mlx-community/Qwen3.5-9B-MLX-4bit"
    GEMMA_MODEL = ""

    def __init__(
        self,
        pdf_path:str,
        output_dir: Path,
        dpi: int = 200,
        max_tokens: int = 8192,
        temperature: float = 0.0,
        prompt: str = None,
        overwrite: bool = False,
        model_name: str = None,
        log_level: int = logging.INFO
    ) -> None:
        method="__init__"

        self.model_name = model_name or self.DEFAULT_MODEL
        self.output_dir = Path(output_dir)
        self.pdf_path = Path(pdf_path)
        self.dpi = dpi
        self.max_tokens = max_tokens
        self.temperature = temperature
        self.prompt = prompt or self.DEFAULT_PROMPT
        self.overwrite = overwrite

        self.logger = self._create_logger(log_level)
        self.logger.info(f"{self._class_name}.{method}-START Cargando modelo: {self.model_name}, con path: {output_dir} y fichero: {pdf_path}")

        if not pdf_path.exists():
            raise FileNotFoundError(f"{self._class_name}.{method}- No existe el PDF: {pdf_path}")

        if not self.output_dir.exists():
            self.output_dir.mkdir(parents=True, exist_ok=True)

        self.logger.info(f"{self._class_name}.{method}- cargando el modelo {self.model_name}")
        self.model, self.processor = load(self.model_name)

    ######################################
    ## Métodos privados de la clase
    ######################################

    def _create_logger(self, log_level: int) -> logging.Logger:
        logger = logging.getLogger(self.__class__.__name__)

        if not logger.handlers:
            handler = logging.StreamHandler()
            formatter = logging.Formatter(
                fmt="%(asctime)s %(levelname)s [%(name)s] %(message)s",
                datefmt="%Y-%m-%d %H:%M:%S",
            )
            handler.setFormatter(formatter)
            logger.addHandler(handler)

        logger.setLevel(log_level)
        logger.propagate = False
        return logger

    def _already_done(self, out_file: Path, overwrite: bool) -> bool:
        return out_file.exists() and not overwrite

    def _render_page_to_pil(self, page: fitz.Page, dpi: int) -> Image.Image:
        """
        Renderiza una página PDF a imagen PIL en RGB.
        """
        zoom = dpi / 72.0
        matrix = fitz.Matrix(zoom, zoom)
        pix = page.get_pixmap(matrix=matrix, alpha=False)
        img_bytes = pix.tobytes("png")
        image = Image.open(io.BytesIO(img_bytes)).convert("RGB")
        return image

    def _save_page_image(self, image: Image.Image, output_dir: Path) -> Path:
        """
        Guarda la imagen renderizada de una página en el directorio de salida.
        """
        image_path = output_dir
        image.save(image_path, format="PNG")
        return image_path

    def _save_text(self, text: str, path: Path) -> None:
        path.write_text(text, encoding="utf-8")

    def _split_thinking_and_answer(self, text: str) -> Tuple[str, str]:
        if not text:
            return "", ""

        text = text.strip()
        #pattern = re.compile(r"<think>\s*(.*?)\s*</think>\s*(.*)", re.DOTALL)
        #match = pattern.fullmatch(text)

        #if match:
        #    return match.group(1).strip(), match.group(2).strip()

        #return "", text
        if "</think>" not in text:
            return "", text

        #before, after = text.split("</think>", 1)

        #thinking = re.sub(r"^\s*<think>\s*", "", before).strip()
        #answer = after.strip()

        #return thinking, answer
        pattern = re.compile(r"(?:<think>\s*)?(.*?)\s*</think>\s*(.*)", re.DOTALL)
        match = pattern.fullmatch(text)

        if match:
            return match.group(1).strip(), match.group(2).strip()

    def _build_prompt(self, processor, model, base_prompt: str) -> str:
        """
        Aplica el chat template esperado por mlx-vlm para 1 imagen.
        """
        config = getattr(model, "config", None)
        if config is None:
            raise RuntimeError("No se pudo obtener model.config del modelo cargado.")

        formatted = apply_chat_template(
            processor,
            config,
            base_prompt,
            num_images=1,
        )
        return formatted

    def _transcribe_page(self, image):
        formatted_prompt = self._build_prompt(self.processor, self.model, self.prompt)

        output = generate(
            self.model,
            self.processor,
            formatted_prompt,
            [image],
            max_tokens=self.max_tokens,
            temperature=self.temperature,
            verbose=False,
            # si tu versión lo soporta:
            thinking_budget=64,
            thinking_start_token="<think>",
            thinking_end_token="</think>",
        )

        raw_text = "" if output is None else str(output.text).strip()
        thinking, answer = self._split_thinking_and_answer(raw_text)

        return thinking, answer

    ######################################
    ## Métodos públicos de la clase
    ######################################

    def process_pdf(self,
        start_page: int = None,
        end_page: int = None,
    ) -> None:
        method="process_pdf"

        self.logger.info(f"{self._class_name}.{method}-START procesando fichero {self.pdf_path}")

        #Abrimos el fichero y calculamos las páginas que vamos a procesar.
        doc = fitz.open(self.pdf_path)
        total_pages = len(doc)
        width=len(str(total_pages))
        first = 1 if start_page is None else max(1, start_page)
        last = total_pages if end_page is None else min(total_pages, end_page)
        self.logger.info(f"{self._class_name}.{method}- páginas Inizio={first}, Final={last} de {total_pages}.")

        if first > last:
            raise ValueError(
                f"Rango de páginas inválido: start_page={first}, end_page={last}, total={total_pages}"
            )

        for page_number in range(first, last + 1):
            out_file_txt = self.output_dir / f"pagina_{page_number:0{width}d}.txt"
            out_file_error_txt = self.output_dir / f"pagina_{page_number:0{width}d}_error.txt"
            out_file_txt_thinking = self.output_dir / f"pagina_{page_number:0{width}d}.dbg"
            out_file_png = self.output_dir / f"pagina_{page_number:0{width}d}.png"

            #Preparamos el fichero de imagen
            try:
                page = doc.load_page(page_number - 1)
                image = self._render_page_to_pil(page, dpi=self.dpi)

                if self._already_done(out_file_png, self.overwrite):
                    self.logger.info(f"{self._class_name}.{method}- [SKIP] Ya existe: {out_file_png}")
                else:
                    self._save_page_image(image, out_file_png)
            except Exception as e:
                error_file = self.output_dir / f"pagina_{page_number}_error_png.txt"
                msg = f"Error en página {page_number}: {e}\n"
                self._save_text(msg, error_file)
                self.logger.error(f"{self._class_name}.{method}-ERROR {msg}")

            #Preparamos el fichero de texto con el LLM.
            if self._already_done(out_file_txt, self.overwrite):
                self.logger.info(f"{self._class_name}.{method}- [SKIP] Ya existe: {out_file_txt}")
                continue

            #Detectamos en la fase de generación si hay una respuesta anómala y se vuelve a generar.
            error = True
            max_retries = 3
            retries = 0

            while error and retries < max_retries:
                self.logger.info(f"{self._class_name}.{method}- Transcribiendo página {page_number}...")
                thinking, text = self._transcribe_page(image)
                text_clean = text.lstrip() if isinstance(text, str) else ""
                retry_needed = (thinking in (None, "")
                    or text_clean.startswith("The user")
                    or text_clean.startswith("<thinking>"))

                if not retry_needed:
                    self._save_text(text_clean, out_file_txt)
                    error = False
                    #self._save_text(thinking, out_file_txt_thinking)
                else:
                    retries += 1
                    self.logger.warning(f"{self._class_name}.{method}- Respuesta inválida en página {page_number}. Reintento {retries}/{max_retries}. Thinking={thinking}, Text={text_clean}")

            if error:
                self.logger.error(f"{self._class_name}.{method}- No se pudo transcribir correctamente la página {page_number}")
                text_clean="ERROR transcribiendo la página."
                self._save_text(text_clean, out_file_error_txt)

        doc.close()
        self.logger.info(f"{self._class_name}.{method}- Proceso finalizado")

    def genera_docx(self) -> Path:
        """
        Recorre un directorio, recoge todos los .txt ordenados por nombre
        y los combina en un .docx con el mismo nombre que el directorio.

        Ejemplo:
        /ruta/salida/mi_pdf/
            pagina_0001.txt
            pagina_0002.txt

        genera:
        /ruta/salida/mi_pdf/mi_pdf.docx
        """
        method="genera_docx"
        output_dir = self.output_dir

        txt_files = sorted(output_dir.glob("*.txt"), key=lambda p: p.name)

        if not txt_files:
            raise FileNotFoundError(f"{self._class_name}.{method}-ERROR No se encontraron ficheros .txt en: {output_dir}")

        #Creamos un documento nuevo.
        doc = Document()
        doc.add_heading(output_dir.name, level=0)

        for i, txt_file in enumerate(txt_files):
            content = txt_file.read_text(encoding="utf-8").strip()
            doc.add_heading(txt_file.stem, level=1)

            # Añade el contenido del txt
            if content:
                for line in content.splitlines():
                    doc.add_paragraph(line)
            else:
                doc.add_paragraph("")

            # Salto de página entre ficheros, salvo en el último
            #if i < len(txt_files) - 1:
            #    doc.add_page_break()

        docx_path = output_dir / f"{output_dir.name}.docx"
        doc.save(docx_path)

        return docx_path